<?php

//This is autogenerated file for DBG PHP Debugger support
setcookie('DBGSESSID', $launchID . '@clienthost:7869');
?>
<html>
<head>
    <meta http-equiv="Refresh" Content="1;URL=<?= $launch ?>">
</head>
<body>TruStudio: starting debug session...</body>
</html>
